大丈夫そうなので元に戻す

diff --git a/.github/workflows/link-check.yml b/.github/workflows/link-check.yml
--- a/.github/workflows/link-check.yml
+++ b/.github/workflows/link-check.yml
@@ -59,28 +59,28 @@ jobs:
           echo "Checked date: ${{ steps.date.outputs.date }}" >> $RESULT_FILE
           echo "---" >> $RESULT_FILE
           echo \# Link check result >> $RESULT_FILE
-          # while read url
-          # do
-          #   npx blc -gi --requests 1 --user-agent "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1" --filter-level 0 "$url" > tmp.txt || {
-          #     status=$?
-          #     echo "Fail {$status}"
-          #     echo "Target {$url}"
-          #     echo \#\# Target url: "$url" >> $RESULT_FILE
-          #     if [ "`cat tmp.txt | grep 'BROKEN'`" ]; then
-          #       echo \#\#\# Broken >> $RESULT_FILE
-          #       cat tmp.txt | grep 'BROKEN' | cut -c17- | sed "s/^/\* /g" >> $RESULT_FILE
-          #     fi
-          #     if [ "`cat tmp.txt | grep 'ERROR' --ignore-case`" ]; then
-          #       echo \#\#\# Error >> $RESULT_FILE
-          #       cat tmp.txt | grep 'ERROR' --ignore-case | cut -c8- >> $RESULT_FILE
-          #     fi
-          #     echo >> $RESULT_FILE
+          while read url
+          do
+            npx blc -gi --requests 1 --user-agent "Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1" --filter-level 0 "$url" > tmp.txt || {
+              status=$?
+              echo "Fail {$status}"
+              echo "Target {$url}"
+              echo \#\# Target url: "$url" >> $RESULT_FILE
+              if [ "`cat tmp.txt | grep 'BROKEN'`" ]; then
+                echo \#\#\# Broken >> $RESULT_FILE
+                cat tmp.txt | grep 'BROKEN' | cut -c17- | sed "s/^/\* /g" >> $RESULT_FILE
+              fi
+              if [ "`cat tmp.txt | grep 'ERROR' --ignore-case`" ]; then
+                echo \#\#\# Error >> $RESULT_FILE
+                cat tmp.txt | grep 'ERROR' --ignore-case | cut -c8- >> $RESULT_FILE
+              fi
+              echo >> $RESULT_FILE
 
-          #     # BROKEN がなくてもエラーになるケースが稀にある
-          #     # Actions上に表示してデバッグするためcatする
-          #     cat tmp.txt
-          #   }
-          # done < post-list.txt
+              # BROKEN がなくてもエラーになるケースが稀にある
+              # Actions上に表示してデバッグするためcatする
+              cat tmp.txt
+            }
+          done < post-list.txt
           cat $RESULT_FILE
           if [ $status -eq 0 ]; then
             echo "All external links operational" >> $RESULT_FILE
@@ -93,9 +93,9 @@ jobs:
       # historyはGithubで確認できるので十分
       - name: Commit result
         run: |
-          # git add $RESULT_FILE
-          # git commit -m "Update $RESULT_FILE"
-          # git push
+          git add $RESULT_FILE
+          git commit -m "Update $RESULT_FILE"
+          git push
 
       # リンクチェックの結果次第でIssueを発行する
       # メール通知してくれるので exit 1 も残しています。
